### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by Nithinraot** [Nithinraot/SEBC#1]
1. Setting up CM
2. Installation pre-requisite.
a. check vm.swappiness on all your nodes
b.Show the mount attributes of your volume(s)
c.If you have ext-based volumes, list the reserve space setting
d.XFS volumes do not support reserve space
e.Disable transparent hugepage support
f.List your network interface configuration
g.Show that forward and reverse host lookups are correctly resolved
h. Show the nscd service is running
i.Show the ntpd service is running

3. Installing Maria-dB
4. Installing CM

**Comment by Nithinraot** [comment]
d . huge page compaction disabling ->
[root@ip-172-31-5-153 transparent_hugepage]# echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled
[root@ip-172-31-5-153 transparent_hugepage]# echo 'never' > /sys/kernel/mm/transparent_hugepage/defrag

[root@ip-172-31-5-153 transparent_hugepage]# cat enabled
always madvise [never]
[root@ip-172-31-5-153 transparent_hugepage]# cat defrag
always madvise [never]

**Comment by Nithinraot** [comment]
List your network interface configuration

[root@ip-172-31-5-153 transparent_hugepage]# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet 172.31.5.153  netmask 255.255.240.0  broadcast 172.31.15.255
        inet6 fe80::87:3cff:fe92:f5e4  prefixlen 64  scopeid 0x20<link>
        ether 02:87:3c:92:f5:e4  txqueuelen 1000  (Ethernet)
        RX packets 1024  bytes 100945 (98.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 848  bytes 130454 (127.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 64  bytes 5920 (5.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 64  bytes 5920 (5.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by Nithinraot** [comment]
mount ->
/dev/xvda2 on / type xfs (rw,relatime,attr2,inode64,noquota)

Note: make sure we always reclaim around 5% of space which will be utilized by system of type ext2 etc for the additional mount that is available

**Comment by Nithinraot** [comment]
for installing NTPD & NSCD ->
   57  yum install bind-utils
   61  yum install ntpd
   62  yum install nscd
   68  yum install ntp

**Comment by Nithinraot** [comment]
[root@ip-172-31-5-153 ec2-user]# cat /etc/nsswitch.conf | grep hosts
#hosts:     db files nisplus nis dns
hosts:      files dns myhostname

When we use AWS, we are not ideally setting up the /etc/hosts and the reason is the above /etc/nssswitch will take care of FQDN

**Comment by Nithinraot** [comment]
installing maria db:
sudo yum install mariadb-server
sudo service mariadb stop
----------------------------------------------------------------
update /etc/my.cnf ->
socket=/var/lib/mysql/mysql.sock
# Disabling symbolic-links is recommended to prevent assorted security risks
#symbolic-links=0
# Settings user and group are ignored when systemd is used.
# If you need to run mysqld under a different user or group,
# customize your systemd unit file for mariadb according to the
# instructions in http://fedoraproject.org/wiki/Systemd

key_buffer = 16M
key_buffer_size = 32M
max_allowed_packet = 32M
thread_stack = 256K
thread_cache_size = 64
query_cache_limit = 8M
query_cache_size = 64M
query_cache_type = 1

binlog_format = mixed

read_buffer_size = 2M
read_rnd_buffer_size = 16M
sort_buffer_size = 8M
join_buffer_size = 8M

log_bin=/var/lib/mysql/mysql_binary_log
max_connections = 550
innodb_file_per_table = 1
innodb_flush_log_at_trx_commit  = 2
innodb_log_buffer_size = 64M
innodb_buffer_pool_size = 4G
innodb_thread_concurrency = 8
innodb_flush_method = O_DIRECT
innodb_log_file_size = 512M

[mysqld_safe]
log-error=/var/log/mariadb/mariadb.log
pid-file=/var/run/mariadb/mariadb.pid

#
# include all files from the config directory
#
!includedir /etc/my.cnf.d

----------------------------------

sudo systemctl enable mariadb
sudo service mariadb start
sudo /usr/bin/mysql_secure_installation -> here set the username password for root/ create a DB named SCM & user named SCM where cloudera-manager-server will use this db.

get the mysql-connector -> 
wget "https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.46.tar.gz"

tar -xvf mysql-connector-java-5.1.46.tar.gz

copy this connector to /user/share/java ( create this folder if it doesn not exists)
cp mysql-connector-java-5.1.46 /user/share/java/mysql-connector-java

**Comment by Nithinraot** [comment]
install Java ->
wget "http://archive.cloudera.com/director/redhat/7/x86_64/director/cloudera-director.repo"
[root@ip-172-31-5-153 ec2-user]# yum list all | grep oracle-*
oracle-j2sdk1.8.x86_64         1.8.0+update121-1

yum install oracle-j2sdk1.8.x86_64

export JAVA_HOME=/usr/java/jdk1.8.0_121-cloudera
export JRE_HOME=/usr/java/jdk1.8.0_121-cloudera/jre
export PATH=/usr/java/jdk1.8.0_121-cloudera/bin/:/usr/java/jdk1.8.0_121-cloudera/jre/bin/

**Comment by Nithinraot** [comment]
@manojsundaram 

Cloudera manager installation error:
Mon May 14 21:55:33 UTC 2018
Current working directory: /run/cloudera-scm-agent/process/65-hive-metastore-validate
Launching one-off process: /usr/lib64/cmf/service/hive/hive.sh validate_metastore
Mon May 14 21:55:33 UTC 2018
JAVA_HOME=/usr/java/jdk1.8.0_121-cloudera
using /usr/java/jdk1.8.0_121-cloudera as JAVA_HOME
using 5 as CDH_VERSION
using /opt/cloudera/parcels/CDH-5.14.2-1.cdh5.14.2.p0.3/lib/hive as HIVE_HOME
using /run/cloudera-scm-agent/process/65-hive-metastore-validate as HIVE_CONF_DIR
using /opt/cloudera/parcels/CDH-5.14.2-1.cdh5.14.2.p0.3/lib/hadoop as HADOOP_HOME
using /run/cloudera-scm-agent/process/65-hive-metastore-validate/yarn-conf as HADOOP_CONF_DIR
CONF_DIR=/run/cloudera-scm-agent/process/65-hive-metastore-validate
CMF_CONF_DIR=/etc/cloudera-scm-agent
Starting metastore validation

Validating schema version
Exit code: 1
Full log file

**Comment by Nithinraot** [comment]
Got the issue of hive metastore issue resolved by running,
click "create hive metastore table" create hive warehouse directory" under actions of hive.

**Comment by Nithinraot** [comment]
@manojsundaram 

Not able to perform replication of DB. Getting the below error ->

CHANGE MASTER TO MASTER_HOST='ec2-18-220-61-58.us-east-2.compute.amazonaws.com', MASTER_USER='slaveuser', MASTER_PASSWORD='Cloudera', MASTER_LOG_FILE='mysql_binary_log.000007', MASTER_LOG_POS=1550;

180515 21:29:26 [Note] 'CHANGE MASTER TO executed'. Previous state master_host='ip-172-31-5-153.us-east-2.compute.internal', master_port='3306', master_log_file='mysql_binary_log.000007', master_log_pos='2063137'. New state master_host='ec2-18-220-61-58.us-east-2.compute.amazonaws.com', master_port='3306', master_log_file='mysql_binary_log.000007', master_log_pos='1550'.
180515 21:29:29 [Note] Slave SQL thread initialized, starting replication in log 'mysql_binary_log.000007' at position 1550, relay log './mariadb-relay-bin.000001' position: 4
180515 21:29:29 [Note] Slave I/O thread: connected to master 'slaveuser@ec2-18-220-61-58.us-east-2.compute.amazonaws.com:3306',replication started in log 'mysql_binary_log.000007' at position 1550
180515 21:29:29 [ERROR] Slave SQL: Error executing row event: 'Table 'scm.CM_VERSION' doesn't exist', Error_code: 1146
180515 21:29:29 [Warning] Slave: Table 'scm.CM_VERSION' doesn't exist Error_code: 1146
180515 21:29:29 [ERROR] Error running query, slave SQL thread aborted. Fix the problem, and restart the slave SQL thread with "SLAVE START". We stopped at log 'mysql_binary_log.000007' position 1699

**Comment by manojsundaram** [comment]
Assigning it back to you, after our discussion.

**Comment by Nithinraot** [comment]
MSQL replica ->

* Installed mariaDB in 2 hosts.
* Installed mysql java connector in all the participating hosts.
* Updated thc onfiguration file /etc/my.cnf. set the service-id to 2 & 3 respectively for master and slave.
* Started the mysqld service
* On the master MySQL node, granted replication privileges for your replica node:
	* Log in with mysql -u ... -p 
	* mysql> GRANT REPLICATION SLAVE ON *.* TO 'slaveuser'@'%' IDENTIFIED BY 'Cloudera';
	* mysql> SET GLOBAL binlog_format = 'ROW'; 
	* mysql> FLUSH TABLES WITH READ LOCK;
* In a second terminal session, log into the MySQL master and show its status:
	* mysql> SHOW MASTER STATUS;
	* Make note of the file name and byte offset. The replica needs this info to sync to the master.
	* Logout of the second session; remove the lock on the first with mysql> UNLOCK TABLES;
* Login to the replica server and configure a connection to the master:
	* mysql> CHANGE MASTER TO MASTER_HOST='ec2-18-220-61-58.us-east-2.compute.amazonaws.com', MASTER_USER='slaveuser', MASTER_PASSWORD='Cloudera', MASTER_LOG_FILE='mysql_binary_log.000007', MASTER_LOG_POS=1550;;
* Initiate slave operations on the replica
	* mysql> START SLAVE;
	* mysql> SHOW SLAVE STATUS \G
* run this from slave to get the db and tables -> mysqldump -h 172.31.5.153 -u root -p --databases scm > scm.sql

* run this from slavemysqldump -u root -p scm  > scm.sql

**Comment by wangbo-cn** [comment]
> 通过运行解决了配置单元metastore问题，在
> 配置单元的动作下单击“创建配置单元metastore表”，“创建配置单元仓库目录”。
I also encountered the same problem, I want your help。
